# HLint configuration file
# https://github.com/ndmitchell/hlint

- arguments: [--color=auto, -XDataKinds, -XDeriveFoldable, -XDeriveFunctor, -XDeriveGeneric, -XDeriveTraversable, -XFlexibleContexts, -XFlexibleInstances, -XMultiParamTypeClasses, -XOverloadedStrings, -XRecordWildCards, -XStandaloneDeriving, -XStrictData, -XTypeApplications]

# Blacklist some functions by default.
- functions:
  - {name: unsafePerformIO, within: [Data.Scientific.Exts]} # unsafePerformIO has to be explicitly whitelisted
  - {name: unsafeCoerce, within: []} # unsafeCoerce has to be explicitly whitelisted
