#!/bin/bash
# Usage: script/repl [ARGS...]
# Run a repl session capable of loading all of the packages and their individual components. Any passed arguments, e.g. module names or flags, will be passed to ghci.

set -e

cd $(dirname "$0")/..

repl_builddir=dist-newstyle

cabal v2-build --builddir="$repl_builddir" all --only-dependencies

cabal v2-exec --builddir="$repl_builddir" env -- -u GHC_ENVIRONMENT ghci -ghci-script=.ghci.semantic $(script/ghci-flags --builddir "$repl_builddir") -no-ignore-dot-ghci $@
